### ISSUE TITLE
Error `Could not execute request! (invalid character '<' looking for beginning of value)` is giving me a trouble

### ISSUE THREAD

**Issue by Glavic** [beldur/kraken-go-api-client#20]
Hi,
I sometimes get error `Could not execute request! (invalid character '<' looking for beginning of value)`.

This error is coming from function `doRequest()`: https://github.com/beldur/kraken-go-api-client/blob/master/krakenapi.go#L354

Problem that I have witnessed is that request was made successfully (`AddOrder()` was successfully), and lib returned this error. My script is retrying to make an `AddOrder()` call if error is returned from `doRequest()`, so you see my frustration when multiple `AddOrder()` return error, but they were succesfull :(

**Comment by beldur** [comment]
Do you have an idea in what kind of situation this error occurs?

**Comment by Glavic** [comment]
It is random...
I **guess** when API performance is degraded on Kraken and `http.Client{}` timeouts kick-in in the middle of the response?

**Comment by beldur** [comment]
I think the question is, if the library should support the Kraken API Request Rate Limits.
See here: https://support.kraken.com/hc/en-us/articles/206548367-What-is-the-API-call-rate-limit-

**Comment by Glavic** [comment]
I really don't know what does API request rate limits have to do with this error?
If I would, for example, hit rate limit, Kraken API should return an error saying that is hit rate limit, and that I should try again later.

**Comment by Glavic** [comment]
In `doRequest()` function I numbered all the returned errors, so I could find out which is the problem:

	err = json.Unmarshal(body, &jsonData)
	if err != nil {
		return nil, fmt.Errorf("Could not execute request #4! (%s) %v", err.Error(), string(body))
	}

and I have printed `body` in the error.

The return I'm having is:

`Could not execute request #4! (invalid character '<' looking for beginning of value) <!DOCTYPE html>`

Why would Kraken API return `<!DOCTYPE html>` ??

**Comment by Glavic** [comment]
It returns: https://pastebin.com/pbtLCxV3
Based on that it is KRAKEN's fault ?

**Comment by Glavic** [comment]
I suppose Kraken or Cloudflare are having some technical issues...
I get bunch of error status codes when calling API:
- 502 Bad Gateway
- 504 Gateway Timeout
- 504
- 520
- 521
- 522
- 524
- 525

**Comment by beldur** [comment]
It seems Kraken is aware of the problem:

https://blog.kraken.com/post/1234/announcement-delisting-pairs-and-temporary-suspension-of-advanced-order-types/

The "fix" is interesting though ;)
