### ISSUE TITLE
Withdraw Private Method Missing?

### ISSUE THREAD

**Issue by tjfi222** [beldur/kraken-go-api-client#24]
Is there a reason the "Withdraw" method is not in the private query method struct?

**Comment by Glavic** [comment]
Because Kraken doesn't support it. See API manual = https://www.kraken.com/help/api

**Comment by Glavic** [comment]
> Private user funding
NOTE:This is a tentative funding API and may be updated in the future. Please refer to the main API page for more information on using the API.

But I see no reason why they are not added...

**Comment by tjfi222** [comment]
Thanks for the quick response.  Will close issue once the merge is complete.

**Comment by beldur** [comment]
Merged. Thx for the feedback!
