### ISSUE TITLE
How to create method Trades  (like Time(), Assets(), etc)

### ISSUE THREAD

**Issue by Glavic** [beldur/kraken-go-api-client#3]
I don't know how to create type for unassociated array like in function [Trades()](https://www.kraken.com/help/api#get-recent-trades).

```
<pair_name> = pair name
         array of array entries(<time>, <bid>, <ask>)
```

Can u give me any suggestions/help?

**Comment by beldur** [comment]
I added the `Trades` Call as an API Method: https://github.com/beldur/kraken-go-api-client/commit/7dcae7acc6366669d9b763f58dc2ecde3d3a7e29

For usage you can look into the test method.

Does this answer your question?

**Comment by Glavic** [comment]
Nice.
I created small modification. What do you think?
https://github.com/Glavic/kraken-go-api-client/commit/4a2fb9415521799a77d8d73e1414055d656db6a7

**Comment by beldur** [comment]
Yes looks good!

PR appreciated :sunny:

**Comment by Glavic** [comment]
Hi, me again.
Just thinking that float is not a got variable for storing sensitive information like Price, Volume and Time in Trades() function. Kraken returns strings (and for a good reason) and u convert it to float64 :(
We could solve this problem with Rational struct (RAT) or plug-in like this: https://github.com/shopspring/decimal
Whay say u?

**Comment by beldur** [comment]
Hi,

I'm a bit reluctant to add a dependency to another package, but I agree that `float` is the wrong type. Maybe we can use `int`? The number of decimals can be queried from Kraken `Assets` API call.

What do you think?

**Comment by rikonor** [comment]
Sorry to barge in but, out of curiosity, what's wrong with keeping it as
floats?

**Comment by beldur** [comment]
I quote here directly from the decimal project:

> Because float64s (or any binary floating point type, actually) can't represent numbers such as 0.1 exactly.
> Consider this code: https://play.golang.org/p/TQBd4yJe6B

**Comment by Glavic** [comment]
I agree that using other plug-ins isn't great idea; I just linked it if there is some idea to "borrow"...
Are u thinking of running `Assets()` every time `Trades()` is called? Or we could just use max decimals for all assets (for example 10)? Just hope that `int64` will be enough.

**Comment by Glavic** [comment]
For `Time` we could just use μs.

**Comment by beldur** [comment]
If you call `Assets` for `Trades` you are in danger of messing up rate limiting tracking for consumers of the API. ([Kraken Rate Limiting](https://support.kraken.com/hc/en-us/articles/206548367-What-is-the-API-call-rate-limit-))

So I would keep the responsibility to the API consumer to know that eg. EUR has to be divided by 5 (197001100 / 5 = 1970.011 EUR) while JPY has to be divided by 3 (261531900 / 3 = 261531.9 JPY).

Another option would be to change the type to string and let the consumer decide how to deal with it.

**Comment by Glavic** [comment]
> So I would keep the responsibility to the API consumer to know that eg. EUR has to be divided by 5 (197001100 / 5 = 1970.011 EUR) while JPY has to be divided by 3 (261531900 / 3 = 261531.9 JPY).
But how will u know in `Trades()` how much decimals has EUR or JPY? I would not go into hardcoding those values, since they can change in the future...

On other hand, more than I think about it, it would be better to let API consumer decide what to do with the data received from Kraken API...

**Comment by beldur** [comment]
> On other hand, more than I think about it, it would be better to let API consumer decide what to do with the data received from Kraken API...

I updated the code accordingly https://github.com/beldur/kraken-go-api-client/commit/0d429b84b3978e1a9f8216072eb8411e6acbe136

**Comment by Glavic** [comment]
I would leave it as it is, only string; and let consumer do the magic with it :)
