### ISSUE TITLE
Add function GetPairTickerInfo in type

### ISSUE THREAD

**Issue by Archie1978** [beldur/kraken-go-api-client#31]
Hello Beldur,
   I saw that you were working on it again.

Can you create this function ? It's easier to use.

func (v *krakenapi.TickerResponse)GetPairTickerInfo(field string) (krakenapi.PairTickerInfo) {
    r := reflect.ValueOf(v)
    f := reflect.Indirect(r).FieldByName(field)
    return f.Interface().(krakenapi.PairTickerInfo)
}

Kinds, regard

**Comment by beldur** [comment]
Closed with https://github.com/beldur/kraken-go-api-client/commit/a3aa238d0b4241f25f8cf61ae1dd5eb434f9c178

Thanks for your feedback!
