### ISSUE TITLE
AssetPair XETCXUSD should be XETCZUSD

### ISSUE THREAD

**Issue by simon-schreiber** [beldur/kraken-go-api-client#40]
If I'm not mistaken the AssetPair XETCXUSD defined in types.go should actually be XETCZUSD

https://api.kraken.com/0/public/AssetPairs

Thanks!

**Comment by beldur** [comment]
Hi simon,

thanks for the input. Could you create a Pull request with an appropriate fix?

**Comment by ElrinV** [comment]
Hi there,
I was adding a bunch of new trading pairs anyways, and noticed the typo as well. I have created a pull request for that change that includes fixing this.

**Comment by beldur** [comment]
Fixed with 55eae997966593e8a96421aad9fbb957bc6cfd31
