### ISSUE TITLE
Trade info totally broken

### ISSUE THREAD

**Issue by damntoken** [beldur/kraken-go-api-client#41]
https://www.kraken.com/help/api#get-recent-trades
States in one ecample 'since' => '137589964200000000'));
Since is a 18 place string timestamp, not 10.
krakenapi.fo file has:
values.Set("since", strconv.FormatInt(since, 10))
Should be to 18, not 10.. or response has times offset by years.

Also beware kraken api docs state:
NOTE: the 'since' parameter is subject to change in the future: it's precision may be modified, and it may no longer be representative of a timestamp. The best practice is to base it on the 'last' value returned in the result set.

**Comment by beldur** [comment]
Hi damntoken,

thanks for the input. Could you create a Pull request with an appropriate fix?

**Comment by gadfly16** [comment]
Hi, I think it's utter nonsense and should be closed as such. The second argument of `strconv.FormatInt` is the __base__ that you want to convert to.
