### ISSUE TITLE
Could not execute request #5! (Response Content-Type is 'text/html', but should be 'application/json'.)

### ISSUE THREAD

**Issue by sacarlson** [beldur/kraken-go-api-client#43]
I am getting this result intermittently  some times 6 times in a row with samples every 5 minutes:

Result: map[XXBTZEUR:map[h:[3200.00000 3228.90000] b:[3184.60000 1 1.000] c:[3188.50000 0.04743778] v:[106.82930320 6371.08316388] p:[3191.29123 3169.57439] t:[593 16441] a:[3188.20000 1 1.000] l:[3181.20000 3109.50000] o:3196.50000]]
2019/01/18 09:16:18 Could not execute request #5! (Response Content-Type is 'text/html', but should be 'application/json'.)

it will later work as many as 6 times before another failure.
I noticed it from a package that uses your client https://github.com/interstellar/kelp that is a trading bot for stellar.org trading platform.  I put in a bug report there at kelp but was told it was not there code by the developers.   I isolated the results coming from your code.  I went and ran your main test and see the same results above.

I compiled your simple main test with go version  go1.11.4 linux/amd64 running on Linux Mint

Sorry I'm not much of a go programmer so not sure I can be of much help to you.   We are still making use of your client even in it's present state with just more samples and allowing up to 6 failures before we delete all offers.

**Comment by sacarlson** [comment]
I"ve collected a bit more information with an added print statement added in your code at the time of error I see this in returned body:
Added print for test sacarlson body= (<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>api.kraken.com | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>
</head>
<body>
<div id="cf-wrapper">
<div id="cf-error-details" class="cf-error-details-wrapper">
<div class="cf-wrapper cf-error-overview">
<h1>
<span class="cf-error-type">Error</span>
<span class="cf-error-code">520</span>
<small class="heading-ray-id">Ray ID: 49b89e16ee8549d3 &bull; 2019-01-19 10:28:58 UTC</small>
</h1>
<h2 class="cf-subheadline">Web server is returning an unknown error</h2>
</div>
<div class="cf-section cf-highlight cf-status-display">
<div class="cf-wrapper">
<div class="cf-columns cols-3">
<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-browser"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc">You</span>
<h3 class="cf-status-name">Browser</h3>
<span class="cf-status-label">Working</span>
</div>
<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-cloud"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc">Bangkok</span>
<h3 class="cf-status-name">Cloudflare</h3>
<span class="cf-status-label">Working</span>
</div>
<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-server"></i>
<i class="cf-icon-status cf-icon-error"></i>
</div>
<span class="cf-status-desc">api.kraken.com</span>
<h3 class="cf-status-name">Host</h3>
<span class="cf-status-label">Error</span>
</div>
</div>
</div>
</div>
<div class="cf-section cf-wrapper">
<div class="cf-columns two">
<div class="cf-column">
<h2>What happened?</h2>
<p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
</div>
<div class="cf-column">
<h2>What can I do?</h2>
<h5>If you are a visitor of this website:</h5>
<p>Please try again in a few minutes.</p>
<h5>If you are the owner of this website:</h5>
<p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team. Please include the Ray ID (which is at the bottom of this error page).</span> <a href="https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520">Additional troubleshooting resources</a>.</p>
</div>
</div>
</div>
<div class="cf-error-footer cf-wrapper">
<p>
<span class="cf-footer-item">Cloudflare Ray ID: <strong>49b89e16ee8549d3</strong></span>
<span class="cf-footer-separator">&bull;</span>
<span class="cf-footer-item"><span>Your IP</span>: 223.204.248.153</span>
<span class="cf-footer-separator">&bull;</span>
<span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
</p>
</div>
</div>
</div>
</body>
</html>
) 
2019/01/19 17:28:59 Could not execute request #5! (Response Content-Type is 'text/html', but should be 'application/json'.)
 ***************************

So from this should we assume it's not your code causing the problem but some flaw on the kraken server side?

**Comment by Glavic** [comment]
> So from this should we assume it's not your code causing the problem but some flaw on the kraken server side?

Yes :(

**Comment by beldur** [comment]
Hi, yes this seems to be an issue on kraken's side.

**Comment by sowmitranalla** [comment]
Just curious, was there any resolution on this? I'm still seeing this error on my end.

**Comment by devstein** [comment]
@sowmitranalla From my experience, this is caused by intermittent issues (5xx errors) on Kraken's side

**Comment by sowmitranalla** [comment]
Thanks for the feedback, we've seen random errors as well. 🤷🏾‍♂️
