### ISSUE TITLE
How to override http.Client{} with custom one?

### ISSUE THREAD

**Issue by Glavic** [beldur/kraken-go-api-client#6]
If API consumer needs to change timeouts, proxy, or what ever else on `http.Client{}` he cannot do this atm.

I would suggest to make `KrakenApi struct` public and that would probably solve all problems?
For example: https://github.com/Glavic/kraken-go-api-client/commit/b60b3819bce6afb919764e87c90eccb06aecff43

Any other ideas?

**Comment by beldur** [comment]
What about a new Method krakenapi.NewWithClient(key, secret, yourOwnHTTPClient). Would that help?

**Comment by Glavic** [comment]
Yes, that would also solve the problem.

**Comment by Khezen** [comment]
Just submitted a PR to solve this issue. Is this solution  is ok with you guys?
